### ISSUE TITLE
PHP5 zval 结构体大小的问题

### ISSUE THREAD

**Issue by tangl163** [laruence/php7-internal#46]
"首先这个结构体的大小是(在64位系统)24个字节, 我们仔细看这个zval.value联合体, **其中zend_object_value是最大的长板**, 它导致整个value需要16个字节"

```c
union {
    long lval;
    double dval;
    struct {
        char *val;
        int len;
    } str;
    HashTable *ht;
    zend_object_value obj;
    zend_ast *ast;
} value;
```

在`union.str` 中有两个成员， 字符型指针 `val` 占8个字节，整型 `len` 占4个字节，加上自动补齐。
`str` 结构体一共占16个字节。

所以，我的问题是：为什说 “`zval.value`联合体, 其中`zend_object_value`是最大的长板, 它导致整个value需要16个字节”。如果我的理解有错误，还请鸟哥纠正我。

**Comment by laruence** [comment]
最长, 但不是唯一 :)
